import { Injectable } from '@angular/core';
import { Product } from './product';

@Injectable({
  providedIn: 'root'
})
export class ProductService {

  private products: Product[] = [
    {
      code: 'LJ15315A - 1 1/2',
      name: 'Adjustable Rail Support Radiused "Internal Fit"',
      dimensions: 'Tube Size x ØR',
      spec: '1 1/2"x R 1 1/2"',
      photo: "products/LJ15315A.png",
      tag: ["Adjustable Support", "Tube Fittings"],
    },
    {
      code: 'LJ15315A - 2',
      name: 'Adjustable Rail Support Radiused "Internal Fit"',
      dimensions: 'Tube Size x ØR',
      spec: '1 1/2"x R 2"',
      photo: "products/LJ15315A.png",
      tag: ["Adjustable Support", "Tube Fittings"]
    },
    {
      code: 'LJ20315A - 2',
      name: 'Adjustable Rail Support Radiused "Internal Fit"',
      dimensions: 'Tube Size x ØR',
      spec: '2"x R 2"',
      photo: "products/LJ15315A.png",
      tag: ["Adjustable Support", "Tube Fittings"]
    },
    {
      code: 'LJ20135AP',
      name: 'Adjustable Rail Support Flat "Internal Fit"',
      dimensions: 'Tube Size x ØR',
      spec: '2" x FLAT',
      photo: "products/LJ20135AP.png",
      tag: ["Adjustable Support", "Tube Fittings"]
    },
    {
      code: 'LJ20136A - 2',
      name: 'Adjustable Rail Support Radius "External Fit"',
      dimensions: 'Tube Size x ØR',
      spec: '2"x R 2"',
      photo: "products/LJ15315A.png",
      tag: ["Adjustable Support", "Tube Fittings"]
    },
    {
      code: 'LJ20136AP',
      name: 'Adjustable Rail Support Flat "External Fit"',
      dimensions: 'Tube Size x ØR',
      spec: '2"x FLAT',
      photo: "products/LJ20136AP.png",
      tag: ["Adjustable Support", "Tube Fittings"]
    },
    {
      code: 'LJ15710RB - 1 1/2"',
      name: 'Adjustable Rail Support Radiused, Type 1',
      dimensions: 'Tube Size x ØR',
      spec: '1 1/2"x R 1 1/2"',
      photo: "products/LJ15710RB.png",
      tag: ["Adjustable Support", "Tube Fittings"]
    },
    {
      code: 'LJ15710RB - 2"',
      name: 'Adjustable Rail Support Radiused, Type 1',
      dimensions: 'Tube Size x ØR',
      spec: '1 1/2"x R 2"',
      photo: "products/LJ15710RB.png",
      tag: ["Adjustable Support", "Tube Fittings"]
    },
    {
      code: 'LJ20710RB - 1 1/2"',
      name: 'Adjustable Rail Support Radiused, Type 1',
      dimensions: 'Tube Size x ØR',
      spec: '2"x R 1 1/2"',
      photo: "products/LJ15710RB.png",
      tag: ["Adjustable Support", "Tube Fittings"]
    },
    {
      code: 'LJ20710RB - 2"',
      name: 'Adjustable Rail Support Radiused, Type 1',
      dimensions: 'Tube Size x ØR',
      spec: '2"x R 2"',
      photo: "products/LJ15710RB.png",
      tag: ["Adjustable Support", "Tube Fittings"]
    },
    {
      code: 'LJ15711RB - 1 1/2"',
      name: 'Adjustable Rail Support Radiused, Type 2',
      dimensions: 'Tube Size x ØR',
      spec: '1 1/2"x R 1 1/2"',
      photo: "products/LJ15711RB.png",
      tag: ["Adjustable Support", "Tube Fittings"]
    },
    {
      code: 'LJ20711RB - 2"',
      name: 'Adjustable Rail Support Radiused, Type 2',
      dimensions: 'Tube Size x ØR',
      spec: '2"x R 2"',
      photo: "products/LJ15711RB.png",
      tag: ["Adjustable Support", "Tube Fittings"]
    },
    //===============Flush Joiner===============
    {
      code: 'LJ1002E',
      name: 'Flush Joiner (90° ell) , Type 1',
      dimensions: 'Tube Size',
      spec: '1"',
      photo: 'products/LJ1002E.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1502E',
      name: 'Flush Joiner (90° ell) , Type 1',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ1002E.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ2002E',
      name: 'Flush Joiner (90° ell) , Type 1',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: 'products/LJ1002E.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1003E',
      name: 'Flush Joiner (135°)',
      dimensions: 'Tube Size',
      spec: '1"',
      photo: 'products/LJ1003E.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1503E',
      name: 'Flush Joiner (135°)',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ1003E.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ2003E',
      name: 'Flush Joiner (135°)',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: 'products/LJ1003E.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1502-1E',
      name: 'Flush Joiner Long Radius (90° ell)',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ1502.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ2002-1E',
      name: 'Flush Joiner Long Radius (90° ell)',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: 'products/LJ1502.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1004E',
      name: 'Flush Joiner "In-Line"',
      dimensions: 'Tube Size',
      spec: '1"',
      photo: 'products/LJ1004E.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1204E',
      name: 'Flush Joiner "In-Line"',
      dimensions: 'Tube Size',
      spec: '1 1/4"',
      photo: 'products/LJ1004E.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1504E',
      name: 'Flush Joiner "In-Line"',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ1004E.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ2004E',
      name: 'Flush Joiner "In-Line"',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: 'products/LJ1004E.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1005E',
      name: 'Flush Joiner "Tee"',
      dimensions: 'Tube Size',
      spec: '1"',
      photo: 'products/LJ1005E.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1505E',
      name: 'Flush Joiner "Tee"',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ1005E.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ2005E',
      name: 'Flush Joiner "Tee"',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: 'products/LJ1005E.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1006E',
      name: 'Flush Joiner (90° Tee)',
      dimensions: 'Tube Size',
      spec: '1"',
      photo: 'products/LJ1006E.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1506E',
      name: 'Flush Joiner (90° Tee)',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ1006E.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ2006E',
      name: 'Flush Joiner (90° Tee)',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: 'products/LJ1006E.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1507E',
      name: 'Flush Joiner (135° Tee)',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ1507E.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ2007E',
      name: 'Flush Joiner (135° Tee)',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: 'products/LJ1507E.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1508E',
      name: 'Flush Joiner "4-Way Tee"',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ1508E.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ2008E',
      name: 'Flush Joiner "4-Way Tee"',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: 'products/LJ1508E.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1509E',
      name: 'Flush Joiner "135° Star"',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ1509E.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ2009E',
      name: 'Flush Joiner "135° Star"',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: 'products/LJ1509E.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1010E',
      name: 'Flush Joiner "4-Way Star"',
      dimensions: 'Tube Size',
      spec: '1"',
      photo: 'products/LJ1010E.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1510E',
      name: 'Flush Joiner "4-Way Star"',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ1010E.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ2010E',
      name: 'Flush Joiner "4-Way Star"',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: 'products/LJ1010E.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1511E',
      name: 'Flush Side Outlet Cross',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ1511E.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ2011E',
      name: 'Flush Side Outlet Cross',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: 'products/LJ1511E.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1512E',
      name: 'Flush Star',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ1512E.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ2012E',
      name: 'Flush Star',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: 'products/LJ1512E.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ2002H1',
      name: 'FLUSH JOINER "90°" (SINGLE SLOT)',
      dimensions: 'Tube Size',
      spec: '2" single slot x 1.5t',
      photo: 'products/LJ2002H1.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ2005H1H2',
      name: 'FLUSH JOINER "TEE"',
      dimensions: 'Tube Size',
      spec: '2" dbl/single slot x 1.5t',
      photo: 'products/LJ2005H1H2.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1522E',
      name: 'Adjustable Ell, Type 1',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ1522E.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ2022E',
      name: 'Adjustable Ell, Type 1',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: 'products/LJ1522E.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1523E',
      name: 'Adjustable Ell, Type 2',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ1523E.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ2023E',
      name: 'Adjustable Ell, Type 2',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: 'products/LJ1523E.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1502U',
      name: 'Flush Joiner (90° ell) , Type 2',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ1502U.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ2002U',
      name: 'Flush Joiner (90° ell) , Type 2',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: 'products/LJ1502U.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1018A',
      name: 'End Cap "Dome"',
      dimensions: 'Tube Size',
      spec: '1"',
      photo: 'products/LJ1018A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1218A',
      name: 'End Cap "Dome"',
      dimensions: 'Tube Size',
      spec: '1 1/4"',
      photo: 'products/LJ1018A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1518A',
      name: 'End Cap "Dome"',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ1018A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ2018A',
      name: 'End Cap "Dome"',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: 'products/LJ1018A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1019A',
      name: 'End Cap "Flat", Type 1',
      dimensions: 'Tube Size',
      spec: '1"',
      photo: 'products/LJ1019A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1219A',
      name: 'End Cap "Flat", Type 1',
      dimensions: 'Tube Size',
      spec: '1 1/4"',
      photo: 'products/LJ1019A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1519A',
      name: 'End Cap "Flat", Type 1',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ1019A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ2019A',
      name: 'End Cap "Flat", Type 1',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: 'products/LJ1019A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ2019H1',
      name: 'END CAP "FLAT"',
      dimensions: 'Tube Size',
      spec: '2" single slot x 1.5t',
      photo: 'products/LJ2019H1.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ2019H2-1',
      name: 'END CAP "FLAT"',
      dimensions: 'Tube Size',
      spec: '2" 1800 dbl slot x 1.5t',
      photo: 'products/LJ2019H1.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ2019H2-2',
      name: 'END CAP "FLAT"',
      dimensions: 'Tube Size',
      spec: '2" 900 dbl slot x 1.5t',
      photo: 'products/LJ2019H1.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1030A',
      name: 'End Cap "Light Knock-In"',
      dimensions: 'Tube Size',
      spec: '1"',
      photo: 'products/LJ1030A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1530A',
      name: 'End Cap "Light Knock-In"',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ1030A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ2030A',
      name: 'End Cap "Light Knock-In"',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: 'products/LJ1030A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1525A',
      name: 'Handrail End CAP 45°',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ1525A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ2025A',
      name: 'Handrail End CAP 45°',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: 'products/LJ1525A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1526A',
      name: 'Handrail End CAP 90°',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ1526A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ2026A',
      name: 'Handrail End CAP 90°',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: 'products/LJ1526A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ15739A',
      name: 'Handrail End Cap 90° Radiused Internal Fit',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ15739A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ20739A',
      name: 'Handrail End Cap 90° Radiused Internal Fit',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: 'products/LJ15739A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1519U',
      name: 'End Cap "Flat", Type 2',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ1519U.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ2019U',
      name: 'End Cap "Flat", Type 2',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: 'products/LJ1519U.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1014A',
      name: 'Oblong Base Plate / Flange',
      dimensions: 'Tube Size',
      spec: '1"',
      photo: 'products/LJ1014A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1214A',
      name: 'Oblong Base Plate / Flange',
      dimensions: 'Tube Size',
      spec: '1 1/4"',
      photo: 'products/LJ1014A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1514A',
      name: 'Oblong Base Plate / Flange',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ1014A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ2014A',
      name: 'Oblong Base Plate / Flange',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: 'products/LJ1014A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1015A',
      name: 'Wall Stop Flange',
      dimensions: 'Tube Size',
      spec: '1"',
      photo: 'products/LJ1015A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1215A',
      name: 'Wall Stop Flange',
      dimensions: 'Tube Size',
      spec: '1 1/4"',
      photo: 'products/LJ1015A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1515A',
      name: 'Wall Stop Flange',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ1015A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ2015A',
      name: 'Wall Stop Flange',
      dimensions: 'Tube Size',
      spec: '2" ( 45° )',
      photo: 'products/LJ1015A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ2015C',
      name: 'Wall Stop Flange',
      dimensions: 'Tube Size',
      spec: '2" ( 37° )',
      photo: 'products/LJ1015A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1599A',
      name: 'Round Adjustable Heavy Duty Base Plate',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ1599A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ2099A',
      name: 'Round Adjustable Heavy Duty Base Plate',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: 'products/LJ1599A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1524A',
      name: 'Outsided Wall Flange, Round Base Type 1',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ1524A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ2024A',
      name: 'Outsided Wall Flange, Round Base Type 1',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: 'products/LJ1524A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ15802A',
      name: 'Outsided Wall Flange, Round Base Type 2',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ15802A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ20802A',
      name: 'Outsided Wall Flange, Round Base Type 2',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: 'products/LJ15802A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1001C',
      name: 'Round Base Plate With Cover',
      dimensions: 'Tube Size',
      spec: '1"',
      photo: 'products/LJ1001C.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1201C',
      name: 'Round Base Plate With Cover',
      dimensions: 'Tube Size',
      spec: '1 1/4"',
      photo: 'products/LJ1001C.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1401C',
      name: 'Round Base Plate With Cover',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ1001C.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ2001C',
      name: 'Round Base Plate With Cover',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: 'products/LJ1001C.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ15512A',
      name: 'Round Base Plate - Type 2',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ15512A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ20512A',
      name: 'Round Base Plate - Type 2',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: 'products/LJ15512A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1016A',
      name: 'Flange, Round Base, Type 1',
      dimensions: 'Tube Size',
      spec: '1"',
      photo: 'products/LJ1016A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1216A',
      name: 'Flange, Round Base, Type 1',
      dimensions: 'Tube Size',
      spec: '1 1/4"',
      photo: 'products/LJ1016A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1516A',
      name: 'Flange, Round Base, Type 1',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ1016A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ2016A',
      name: 'Flange, Round Base, Type 1',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: 'products/LJ1016A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1402S',
      name: 'Square Base Plate',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ1402S.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ2002S',
      name: 'Square Base Plate',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: 'products/LJ1402S.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1069',
      name: 'ROUND BASE PLATE (WELD)',
      dimensions: 'Tube Size',
      spec: '1"',
      photo: 'products/LJ1069.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1269',
      name: 'ROUND BASE PLATE (WELD)',
      dimensions: 'Tube Size',
      spec: '1 1/4"',
      photo: 'products/LJ1069.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1569',
      name: 'ROUND BASE PLATE (WELD)',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ1069.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ15803',
      name: 'Outsided Wall Flange, Adjustable, Round Base Type 3',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ15803.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ20803',
      name: 'Outsided Wall Flange, Adjustable, Round Base Type 3',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: 'products/LJ15803.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ2016U',
      name: 'Flange, Round Base, Type 2',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: 'products/LJ2016U.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ15601A',
      name: 'Flange, Round Base, Type 3',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ15601A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ20601A',
      name: 'Flange, Round Base, Type 3',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: 'products/LJ15601A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ15315AC',
      name: 'ROUND BASE "INTERNAL FIT"',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ15315AC.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ20315AC',
      name: 'ROUND BASE "INTERNAL FIT"',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: 'products/LJ15315AC.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ15316AP',
      name: 'FLAT "EXTERNAL FIT"',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ15316AP.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ20316AP',
      name: 'FLAT "EXTERNAL FIT"',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: 'products/LJ15316AP.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ15315A - 1 1/2',
      name: 'Adjustable Rail Support Radiused "Internal Fit"',
      dimensions: 'Tube Size x ØR',
      spec: '1 1/2"x R 1 1/2"',
      photo: 'products/LJ15315A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ15315A - 2',
      name: 'Adjustable Rail Support Radiused "Internal Fit"',
      dimensions: 'Tube Size x ØR',
      spec: '1 1/2"x R 2"',
      photo: 'products/LJ15315A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ20315A - 2',
      name: 'Adjustable Rail Support Radiused "Internal Fit"',
      dimensions: 'Tube Size x ØR',
      spec: '2"x R 2"',
      photo: 'products/LJ15315A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ20135AP',
      name: 'Adjustable Rail Support Flat "Internal Fit"',
      dimensions: 'Tube Size x ØR',
      spec: '2" x FLAT',
      photo: 'products/LJ20135AP.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ20136A - 2',
      name: 'Adjustable Rail Support Radius "External Fit"',
      dimensions: 'Tube Size x ØR',
      spec: '2"x R 2"',
      photo: 'products/LJ20136A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ20136AP',
      name: 'Adjustable Rail Support Flat "External Fit"',
      dimensions: 'Tube Size x ØR',
      spec: '2"x FLAT',
      photo: 'products/LJ20136AP.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ15710RB - 1 1/2"',
      name: 'Adjustable Rail Support Radiused, Type 1',
      dimensions: 'Tube Size x ØR',
      spec: '1 1/2"x R 1 1/2"',
      photo: 'products/LJ15710RB.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ15710RB - 2"',
      name: 'Adjustable Rail Support Radiused, Type 1',
      dimensions: 'Tube Size x ØR',
      spec: '1 1/2"x R 2"',
      photo: 'products/LJ15710RB.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ20710RB - 1 1/2"',
      name: 'Adjustable Rail Support Radiused, Type 1',
      dimensions: 'Tube Size x ØR',
      spec: '2"x R 1 1/2"',
      photo: 'products/LJ15710RB.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ20710RB - 2"',
      name: 'Adjustable Rail Support Radiused, Type 1',
      dimensions: 'Tube Size x ØR',
      spec: '2"x R 2"',
      photo: 'products/LJ15710RB.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ15711RB - 1 1/2"',
      name: 'Adjustable Rail Support Radiused, Type 2',
      dimensions: 'Tube Size x ØR',
      spec: '1 1/2"x R 1 1/2"',
      photo: 'products/LJ15711RB.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ20711RB - 2"',
      name: 'Adjustable Rail Support Radiused, Type 2',
      dimensions: 'Tube Size x ØR',
      spec: '2"x R 2"',
      photo: 'products/LJ15711RB.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ710.381RB',
      name: 'ADJUSTABLE HANDRAIL SUPPORT, RADIUSED',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ710.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ710.424RB',
      name: 'ADJUSTABLE HANDRAIL SUPPORT, RADIUSED',
      dimensions: 'Tube Size',
      spec: '42.4mm',
      photo: 'products/LJ710.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ710.508RB',
      name: 'ADJUSTABLE HANDRAIL SUPPORT, RADIUSED',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: 'products/LJ710.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ20314A-2',
      name: 'Perpendicular Joiner "37° External Cap"',
      dimensions: 'Tube Size x ØR',
      spec: '2" x 2"',
      photo: 'products/LJ20314A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ10313A-1.5',
      name: 'Perpendicular Joiner "External Cap"',
      dimensions: 'Tube Size x ØR',
      spec: '1" - R 1 1/2"',
      photo: 'products/LJ10313A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ10313A-2',
      name: 'Perpendicular Joiner "External Cap"',
      dimensions: 'Tube Size x ØR',
      spec: '1" - R 2"',
      photo: 'products/LJ10313A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ15313A-1.5',
      name: 'Perpendicular Joiner "External Cap"',
      dimensions: 'Tube Size x ØR',
      spec: '1 1/2" - R 1 1/2"',
      photo: 'products/LJ10313A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ15313A-2',
      name: 'Perpendicular Joiner "External Cap"',
      dimensions: 'Tube Size x ØR',
      spec: '1 1/2" - R 2"',
      photo: 'products/LJ10313A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ20313A-2',
      name: 'Perpendicular Joiner "External Cap"',
      dimensions: 'Tube Size x ØR',
      spec: '2" - R 2"',
      photo: 'products/LJ10313A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1527A - 1 1/2',
      name: 'Perpendicular Joiner "Flush Fitting"',
      dimensions: 'Tube Size x ØR',
      spec: '1 1/2" x 1 1/2"',
      photo: 'products/LJ1527A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1527A - 2',
      name: 'Perpendicular Joiner "Flush Fitting"',
      dimensions: 'Tube Size x ØR',
      spec: '1 1/2" x 2"',
      photo: 'products/LJ1527A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ2027A - 2',
      name: 'Perpendicular Joiner "Flush Fitting"',
      dimensions: 'Tube Size x ØR',
      spec: '2" x 2"',
      photo: 'products/LJ1527A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ2027H2',
      name: 'PERPENDICULAR JOINER, FLUSH FITTING (DOUBLE SLOT)',
      dimensions: 'Tube Size',
      spec: '2" double slot x 1.5t',
      photo: 'products/LJ2027H2.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ726.254',
      name: 'PERPENDICULAR JOINER, FLUSH FITTING',
      dimensions: 'Tube Size',
      spec: '1" - R1"',
      photo: 'products/LJ726.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ726.381',
      name: 'PERPENDICULAR JOINER, FLUSH FITTING',
      dimensions: 'Tube Size',
      spec: '1 1/2" - R1 1/2"',
      photo: 'products/LJ726.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ726.424',
      name: 'PERPENDICULAR JOINER, FLUSH FITTING',
      dimensions: 'Tube Size',
      spec: '42.4mm - R42.4mm',
      photo: 'products/LJ726.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },{
      code: 'LJ726.508',
      name: 'PERPENDICULAR JOINER, FLUSH FITTING',
      dimensions: 'Tube Size',
      spec: '2" - R2"',
      photo: 'products/LJ726.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ726.381-2',
      name: 'PERPENDICULAR JOINER, FLUSH FITTING',
      dimensions: 'Tube Size',
      spec: '1 1/2" - R2"',
      photo: 'products/LJ726.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1220A',
      name: 'POST REDUCER, TAPERED',
      dimensions: 'Tube Size',
      spec: '1 1/4" - 5/8"',
      photo: 'products/LJ1220A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1520A',
      name: 'POST REDUCER, TAPERED',
      dimensions: 'Tube Size',
      spec: '1 1/2" - 3/4"',
      photo: 'products/LJ1220A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },{
      code: 'LJ2020A',
      name: 'POST REDUCER, TAPERED',
      dimensions: 'Tube Size',
      spec: '2" - 1"',
      photo: 'products/LJ1220A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ15602',
      name: 'Rail Support Type - 1',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ15602.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ20602',
      name: 'Rail Support Type - 1',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: 'products/LJ15602.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ15603',
      name: 'Rail Support Type - 2',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ15603.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },{
      code: 'LJ20603',
      name: 'Rail Support Type - 2',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: 'products/LJ15603.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1528A',
      name: 'Handrail Wall Support "Radiused"',
      dimensions: 'ØR',
      spec: '1 1/2"',
      photo: 'products/LJ1528A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ2028A',
      name: 'Handrail Wall Support "Radiused"',
      dimensions: 'ØR',
      spec: '2"',
      photo: 'products/LJ1528A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ15710RA 381',
      name: 'Handrail Support "Radiused" Type-2',
      dimensions: 'Tube Size x ØR',
      spec: '1 1/2" x 1 1/2"',
      photo: 'products/LJ15710RA.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },{
      code: 'LJ15710RA 508',
      name: 'Handrail Support "Radiused" Type-2',
      dimensions: 'Tube Size x ØR',
      spec: '1 1/2" x 2"',
      photo: 'products/LJ15710RA.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ20710RA 381',
      name: 'Handrail Support "Radiused" Type-2',
      dimensions: 'Tube Size x ØR',
      spec: '2" x 1 1/2"',
      photo: 'products/LJ15710RA.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ20710RA 508',
      name: 'Handrail Support "Radiused" Type-2',
      dimensions: 'Tube Size x ØR',
      spec: '2" x 2"',
      photo: 'products/LJ15710RA.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ0473A',
      name: 'Cross Saddle',
      dimensions: 'Tube Size x ØR',
      spec: '1/2" x 1 1/2"',
      photo: 'products/LJ0473A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },{
      code: 'LJ0474A',
      name: 'Cross Saddle',
      dimensions: 'Tube Size x ØR',
      spec: '1/2" x 2"',
      photo: 'products/LJ0473A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ0573A',
      name: 'Cross Saddle',
      dimensions: 'Tube Size x ØR',
      spec: '5/8" x 1 1/2"',
      photo: 'products/LJ0473A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ0574A',
      name: 'Cross Saddle',
      dimensions: 'Tube Size x ØR',
      spec: '5/8" x 2"',
      photo: 'products/LJ0473A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ0673A',
      name: 'Cross Saddle',
      dimensions: 'Tube Size x ØR',
      spec: '3/4" x 1 /12"',
      photo: 'products/LJ0473A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },{
      code: 'LJ0674A',
      name: 'Cross Saddle',
      dimensions: 'Tube Size x ØR',
      spec: '3/4" x 2"',
      photo: 'products/LJ0473A.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ0473B',
      name: 'Cross Saddle Blind Hole',
      dimensions: 'Tube Size x ØR',
      spec: '1/2" x 1 1/2"',
      photo: 'products/LJ0473B.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ0474B',
      name: 'Cross Saddle Blind Hole',
      dimensions: 'Tube Size x ØR',
      spec: '1/2" x 2"',
      photo: 'products/LJ0473B.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ0573B',
      name: 'Cross Saddle Blind Hole',
      dimensions: 'Tube Size x ØR',
      spec: '5/8" x 1 1/2"',
      photo: 'products/LJ0473B.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },{
      code: 'LJ0574B',
      name: 'Cross Saddle Blind Hole',
      dimensions: 'Tube Size x ØR',
      spec: '5/8" x 2"',
      photo: 'products/LJ0473B.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ0673B',
      name: 'Cross Saddle Blind Hole',
      dimensions: 'Tube Size x ØR',
      spec: '3/4" x 1 /12"',
      photo: 'products/LJ0473B.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ0674B',
      name: 'Cross Saddle Blind Hole',
      dimensions: 'Tube Size x ØR',
      spec: '3/4" x 2"',
      photo: 'products/LJ0473B.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ15711RA',
      name: 'Handrail Support "Radiused" Type-3',
      dimensions: 'ØR',
      spec: '1 1/2"',
      photo: 'products/LJ15711RA.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ20711RA',
      name: 'Handrail Support "Radiused" Type-3',
      dimensions: 'ØR',
      spec: '2"',
      photo: 'products/LJ15711RA.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ151BK',
      name: 'Handrail Support For Glass, "Radiused" Type 1 (Adjustable)',
      dimensions: 'ØR, Glass (mm)',
      spec: '1 1/2" x 8~12mm',
      photo: 'products/LJ151BK.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ201BK',
      name: 'Handrail Support For Glass, "Radiused" Type 1 (Adjustable)',
      dimensions: 'ØR, Glass (mm)',
      spec: '2" x 8~12mm',
      photo: 'products/LJ151BK.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ152BK',
      name: 'Handrail Support For Glass, "Radiused" Type 2 (Fixed)',
      dimensions: 'ØR, Glass (mm)',
      spec: '1 1/2" x 8~12mm',
      photo: 'products/LJ152BK.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ202BK',
      name: 'Handrail Support For Glass, "Radiused" Type 2 (Fixed)',
      dimensions: 'ØR, Glass (mm)',
      spec: '2" x 8~12mm',
      photo: 'products/LJ152BK.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ155BK',
      name: 'Handrail Support For Glass, "Radiused" Type 3 (Adjustable)',
      dimensions: 'ØR, Glass (mm)',
      spec: '1 1/2" x 8~12mm',
      photo: 'products/LJ155BK.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ205BK',
      name: 'Handrail Support For Glass, "Radiused" Type 3 (Adjustable)',
      dimensions: 'ØR, Glass (mm)',
      spec: '2" x 8~12mm',
      photo: 'products/LJ155BK.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ203BK',
      name: 'Handrail Support For Glass & Wall',
      dimensions: 'ØR, Glass (mm)',
      spec: '8~12mm',
      photo: 'products/LJ203BK.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1523B',
      name: 'Glass Clip, Type 1',
      dimensions: 'Tube Size x Glas',
      spec: 'R 1 1/2"x 8-12 mm',
      photo: 'products/LJ1523B.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ2023B',
      name: 'Glass Clip, Type 1',
      dimensions: 'Tube Size x Glass',
      spec: 'R 2"x 8-12 mm',
      photo: 'products/LJ1523B.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJS71R381',
      name: 'Glass Clamp, Square Type',
      dimensions: 'A x B x D x R x Glass (mm)',
      spec: '45 x 49 x 27 xR 38.1 x 6~10',
      photo: 'products/LJS71R381.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJS71R424',
      name: 'Glass Clamp, Square Type',
      dimensions: 'A x B x D x R x Glass (mm)',
      spec: '45 x 49 x 27 x R 42.4 x 6~10',
      photo: 'products/LJS71R381.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJS71R508',
      name: 'Glass Clamp, Square Type',
      dimensions: 'A x B x D x R x Glass (mm)',
      spec: '45 x 49 x 27 x R 50.8 x 6~10',
      photo: 'products/LJS71R381.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJS72F',
      name: 'Glass Clamp, Square Type',
      dimensions: 'A x B x D x R x Glass (mm)',
      spec: '45 x 45 x 27 x (FLAT) x 6~10 ',
      photo: 'products/LJS71R381.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJS73R381',
      name: 'Glass Clamp, Square Type',
      dimensions: 'A x B x D x R x Glass (mm)',
      spec: '55 x 60 x 33 x R 38.1 x 8~12',
      photo: 'products/LJS71R381.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJS73R424',
      name: 'Glass Clamp, Square Type',
      dimensions: 'A x B x D x R x Glass (mm)',
      spec: '55 x 60 x 33 x R 42.4 x 8~12',
      photo: 'products/LJS71R381.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJS73R508',
      name: 'Glass Clamp, Square Type',
      dimensions: 'A x B x D x R x Glass (mm)',
      spec: '55 x 60 x 33 x R 50.8 x 8~12',
      photo: 'products/LJS71R381.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJS74F',
      name: 'Glass Clamp, Square Type',
      dimensions: 'A x B x D x R x Glass (mm)',
      spec: '55 x 55 x 33 x (FLAT) x 8~12 ',
      photo: 'products/LJS71R381.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ5360F-P',
      name: 'GLASS CLAMP, D TYPE',
      dimensions: 'Tube Size',
      spec: '53 x 60 x 31 x 16 x 8~12',
      photo: 'products/LJ5360F.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ4563F-P',
      name: 'GLASS CLAMP, D TYPE',
      dimensions: 'Tube Size',
      spec: '45 x 63 x 28 x 16 x 6~10',
      photo: 'products/LJ5360F.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ4563R2"-P',
      name: 'GLASS CLAMP, D TYPE',
      dimensions: 'Tube Size',
      spec: '45 x 63 x 28 x 16 x 6~10',
      photo: 'products/LJ5360F.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ4050F',
      name: 'GLASS CLAMP, D TYPE',
      dimensions: 'Tube Size',
      spec: '40 x 50 x 24 x 16 x 6~10',
      photo: 'products/LJ5360F.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ4050R2"',
      name: 'GLASS CLAMP, D TYPE',
      dimensions: 'Tube Size',
      spec: '40 x 50 x 24 x 16 x 6~10',
      photo: 'products/LJ5360F.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ4569F-P',
      name: 'GLASS CLAMP, D TYPE',
      dimensions: 'Tube Size',
      spec: '45 x 69 x 28 x 22 x 8~12',
      photo: 'products/LJ5360F.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJD75R381',
      name: 'Glass Clamp, D Type',
      dimensions: 'A x B x D x R x Glass (mm)',
      spec: '50 x 53 x 33 x R 38.1 x 8~12',
      photo: 'products/LJD75R381.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJD75R424',
      name: 'Glass Clamp, D Type',
      dimensions: 'A x B x D x R x Glass (mm)',
      spec: '50 x 53 x 33 x R 42.4 x 8~12',
      photo: 'products/LJD75R381.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJD75R508',
      name: 'Glass Clamp, D Type',
      dimensions: 'A x B x D x R x Glass (mm)',
      spec: '50 x 53 x 33 x R 50.8 x 8~12',
      photo: 'products/LJD75R381.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJD76F',
      name: 'Glass Clamp, D Type',
      dimensions: 'A x B x D x R x Glass (mm)',
      spec: '65 x 60 x 33 (FLAT) x 8~12',
      photo: 'products/LJD75R381.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJD81R381',
      name: 'Glass Clamp, D Type',
      dimensions: 'A x B x D x R x Glass (mm)',
      spec: '40 x 53 x 23 x R 38.1 x 6~10',
      photo: 'products/LJD75R381.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJD81R424',
      name: 'Glass Clamp, D Type',
      dimensions: 'A x B x D x R x Glass (mm)',
      spec: '40 x 53 x 23 x R 42.4 x 6~10',
      photo: 'products/LJD75R381.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJD81R508',
      name: 'Glass Clamp, D Type',
      dimensions: 'A x B x D x R x Glass (mm)',
      spec: '40 x 53 x 23 x R 50.8 x 6~10',
      photo: 'products/LJD75R381.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJD82F',
      name: 'Glass Clamp, D Type',
      dimensions: 'A x B x D x R x Glass (mm)',
      spec: '40 x 50 x 23 x (FLAT) x 6~10',
      photo: 'products/LJD75R381.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJD83R381',
      name: 'Glass Clamp, D Type',
      dimensions: 'A x B x D x R x Glass (mm)',
      spec: '45 x 66 x 27 x R 38.1 x 8~12',
      photo: 'products/LJD75R381.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJD83R424',
      name: 'Glass Clamp, D Type',
      dimensions: 'A x B x D x R x Glass (mm)',
      spec: '45 x 66 x 27 x R 42.4 x 8~12',
      photo: 'products/LJD75R381.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJD83R508',
      name: 'Glass Clamp, D Type',
      dimensions: 'A x B x D x R x Glass (mm)',
      spec: '45 x 66 x 27 x R 50.8 x 8~12',
      photo: 'products/LJD75R381.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJD84F',
      name: 'Glass Clamp, D Type',
      dimensions: 'A x B x D x R x Glass (mm)',
      spec: '45 x 62 x 27 (FLAT) x 8~12',
      photo: 'products/LJD75R381.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJB90-SH',
      name: 'Glass Clip, Type 2',
      dimensions: 'Size x Glass (mm)',
      spec: '(90 x 50 x 55) x 10~12',
      photo: 'products/LJB90.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJB90G-SH',
      name: 'Glass Clip Type 3',
      dimensions: 'Size x Glass (mm)',
      spec: '(90 x 58 x 55) x 10~12',
      photo: 'products/LJB90G.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    
    {
      code: 'LJ01SPG',
      name: 'Glass Holder Type 1',
      dimensions: 'Glass (mm)',
      spec: '10~12 mm',
      photo: 'products/LJ01SPG.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ03SPG',
      name: 'Glass Holder Type 2',
      dimensions: 'Glass (mm)',
      spec: '10~12 mm',
      photo: 'products/LJ03SPG.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ04SPG',
      name: 'Glass Holder Type 3',
      dimensions: 'Glass (mm)',
      spec: '10~12 mm',
      photo: 'products/LJ04SPG.png',
      tag: ['Flush Joiner', 'Tube Fittings'],
    },
  {
        code: 'LJ2019S',
        name: 'End Cap "Flat"',
        dimensions: 'Tube Size',
        spec: '2" x 2"',
        photo: 'products/LJ2019S.png',
        tag: ['Flush Joiner', 'Tube Fittings'],
      },
      {
        code: 'LJ2004S',
        name: 'Flush Joiner "In-Line"',
        dimensions: 'Tube Size',
        spec: '2" x 2"',
        photo: 'products/LJ2004S.png',
        tag: ['Flush Joiner', 'Tube Fittings'],
      },
      {
        code: 'LJ2002S',
        name: 'Flush Joiner (90°)',
        dimensions: 'Tube Size',
        spec: '2"x 2"',
        photo: 'products/LJ2002S.png',
        tag: ['Flush Joiner', 'Tube Fittings'],
      },
      {
        code: 'LJ2005S',
        name: 'Flush Joiner "Tee"',
        dimensions: 'Tube Size',
        spec: '2"x 2"',
        photo: 'products/LJ2005S.png',
        tag: ['Flush Joiner', 'Tube Fittings'],
      },
      {
        code: 'LJ2006S',
        name: 'Flush Joiner "90° Tee"',
        dimensions: 'Tube Size',
        spec: '2"x 2"',
        photo: 'products/LJ2006S.png',
        tag: ['Flush Joiner', 'Tube Fittings'],
      },
      {
        code: 'LJ2014S',
        name: 'Oblong Base Plate Flange',
        dimensions: 'Tube Size',
        spec: '2"x 2"',
        photo: 'products/LJ2014S.png',
        tag: ['Flush Joiner', 'Tube Fittings'],
      },
      {
        code: 'LJ2016S',
        name: 'Square Base Plate / Flange',
        dimensions: 'Tube Size',
        spec: '2"x 2"',
        photo: 'products/LJ2016S.png',
        tag: ['Flush Joiner', 'Tube Fittings'],
      },
      {
        code: 'LJ2015S',
        name: 'Wall Stop Flange 37°',
        dimensions: 'Tube Size',
        spec: '2"x 2"',
        photo: 'products/LJ2015S.png',
        tag: ['Flush Joiner', 'Tube Fittings'],
      },
      {
        code: 'LJ315APS',
        name: 'Adjustable Rail Support "Flat Top"',
        dimensions: 'Tube Size x ØR',
        spec: '2" x 2" x FLAT',
        photo: 'products/LJ315APS.png',
        tag: ['Flush Joiner', 'Tube Fittings'],
      },
      {
        code: 'LJ2020S',
        name: 'Post Reducer Square "Round In-Line"',
        dimensions: 'Tube Size x ØR',
        spec: '2" x 2" x 2"',
        photo: 'products/LJ2020S.png',
        tag: ['Flush Joiner', 'Tube Fittings'],
      },
      {
        code: 'LJ2021S',
        name: 'Post Reducer Square "Round Adjustable"',
        dimensions: 'Tube Size x ØR',
        spec: '2" x 2" x 2"',
        photo: 'products/LJ2021S.png',
        tag: ['Flush Joiner', 'Tube Fittings'],
      },
      {
        code: 'LJ2022S',
        name: 'Post Rreducer Square "Round 90° Corner"',
        dimensions: 'Tube Size x ØR',
        spec: '2" x 2" x 2"',
        photo: 'products/LJ2022S.png',
        tag: ['Flush Joiner', 'Tube Fittings'],
      },
      {
        code: 'LJ201BL',
        name: 'Rail post Type 1',
        dimensions: 'Glass (mm)',
        spec: '10~12 mm',
        photo: 'products/LJ201BL.png',
        tag: ['Flush Joiner', 'Tube Fittings'],
      },
      {
        code: 'LJ307BL',
        name: 'Rail post Type 2',
        dimensions: 'Glass (mm)',
        spec: '10~12 mm',
        photo: 'products/LJ307BL.png',
        tag: ['Flush Joiner', 'Tube Fittings'],
      },
      {
        code: 'LJ1201GB',
        name: 'Grab Bar',
        dimensions: 'Tube Size x Length',
        spec: '31.8 x 600 mm',
        photo: 'products/LJ1201GB.png',
        tag: ['Flush Joiner', 'Tube Fittings'],
      },
      {
        code: 'LJ1501GB',
        name: 'Grab Bar',
        dimensions: 'Tube Size x Length',
        spec: '38.1 x 600 mm',
        photo: 'products/LJ1201GB.png',
        tag: ['Flush Joiner', 'Tube Fittings'],
      },
      {
        code: 'LJ1201FGB',
        name: 'Folding Grab bar',
        dimensions: 'Tube Size x Length',
        spec: '31.8 x 800 mm',
        photo: 'products/LJ1201FGB.png',
        tag: ['Flush Joiner', 'Tube Fittings'],
      },
    //=============== Flange ===============
    {
      code: 'LJ1014A',
      name: 'Oblong Base Plate / Flange',
      dimensions: 'Tube Size',
      spec: '1"',
      photo: "products/LJ1014A.png",
      tag: ["Flange", "Tube Fittings"]
    },
    {
      code: 'LJ1214A',
      name: 'Oblong Base Plate / Flange',
      dimensions: 'Tube Size',
      spec: '1 1/4"',
      photo: "products/LJ1014A.png",
      tag: ["Flange", "Tube Fittings"]
    },
    {
      code: 'LJ1514A',
      name: 'Oblong Base Plate / Flange',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: "products/LJ1014A.png",
      tag: ["Flange", "Tube Fittings"]
    },
    {
      code: 'LJ2014A',
      name: 'Oblong Base Plate / Flange',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: "products/LJ1014A.png",
      tag: ["Flange", "Tube Fittings"]
    },
    {
      code: 'LJ1015A',
      name: 'Wall Stop Flange',
      dimensions: 'Tube Size',
      spec: '1"',
      photo: "products/LJ1015A.png",
      tag: ["Flange", "Tube Fittings"]
    },
    {
      code: 'LJ1215A',
      name: 'Wall Stop Flange',
      dimensions: 'Tube Size',
      spec: '1 1/4"',
      photo: "products/LJ1015A.png",
      tag: ["Flange", "Tube Fittings"]
    },
    {
      code: 'LJ1515A',
      name: 'Wall Stop Flange',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: "products/LJ1015A.png",
      tag: ["Flange", "Tube Fittings"]
    },
    {
      code: 'LJ2015A',
      name: 'Wall Stop Flange',
      dimensions: 'Tube Size',
      spec: '2" ( 45° )',
      photo: "products/LJ1015A.png",
      tag: ["Flange", "Tube Fittings"]
    },
    {
      code: 'LJ2015C',
      name: 'Wall Stop Flange',
      dimensions: 'Tube Size',
      spec: '2" ( 37° )',
      photo: "products/LJ1015A.png",
      tag: ["Flange", "Tube Fittings"]
    },
    {
      code: 'LJ1599A',
      name: 'Round Adjustable Heavy Duty Base Plate',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: "products/LJ1599A.png",
      tag: ["Flange", "Tube Fittings"]
    },
    {
      code: 'LJ2099A',
      name: 'Round Adjustable Heavy Duty Base Plate',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: "products/LJ1599A.png",
      tag: ["Flange", "Tube Fittings"]
    },
    {
      code: 'LJ1524A',
      name: 'Outsided Wall Flange, Round Base Type 1',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: "products/LJ1524A.png",
      tag: ["Flange", "Tube Fittings"]
    },
    {
      code: 'LJ2024A',
      name: 'Outsided Wall Flange, Round Base Type 1',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: "products/LJ1524A.png",
      tag: ["Flange", "Tube Fittings"]
    },
    {
      code: 'LJ15802A',
      name: 'Outsided Wall Flange, Round Base Type 2',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: "products/LJ15802A.png",
      tag: ["Flange", "Tube Fittings"]
    },
    {
      code: 'LJ20802A',
      name: 'Outsided Wall Flange, Round Base Type 2',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: "products/LJ15802A.png",
      tag: ["Flange", "Tube Fittings"]
    },
    {
      code: 'LJ1001C',
      name: 'Round Base Plate With Cover',
      dimensions: 'Tube Size',
      spec: '1"',
      photo: "products/LJ1001C.png",
      tag: ["Flange", "Tube Fittings"]
    },
    {
      code: 'LJ1201C',
      name: 'Round Base Plate With Cover',
      dimensions: 'Tube Size',
      spec: '1 1/4"',
      photo: "products/LJ1001C.png",
      tag: ["Flange", "Tube Fittings"]
    },
    {
      code: 'LJ1401C',
      name: 'Round Base Plate With Cover',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: "products/LJ1001C.png",
      tag: ["Flange", "Tube Fittings"]
    },
    {
      code: 'LJ2001C',
      name: 'Round Base Plate With Cover',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: "products/LJ1001C.png",
      tag: ["Flange", "Tube Fittings"]
    },
    {
      code: 'LJ15512A',
      name: 'Round Base Plate - Type 2',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: "products/LJ15512A.png",
      tag: ["Flange", "Tube Fittings"]
    },
    {
      code: 'LJ20512A',
      name: 'Round Base Plate - Type 2',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: "products/LJ15512A.png",
      tag: ["Flange", "Tube Fittings"]
    },
    {
      code: 'LJ1016A',
      name: 'Flange, Round Base, Type 1',
      dimensions: 'Tube Size',
      spec: '1"',
      photo: "products/LJ1016A.png",
      tag: ["Flange", "Tube Fittings"]
    },
    {
      code: 'LJ1216A',
      name: 'Flange, Round Base, Type 1',
      dimensions: 'Tube Size',
      spec: '1 1/4"',
      photo: "products/LJ1016A.png",
      tag: ["Flange", "Tube Fittings"]
    },
    {
      code: 'LJ1516A',
      name: 'Flange, Round Base, Type 1',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: "products/LJ1016A.png",
      tag: ["Flange", "Tube Fittings"]
    },
    {
      code: 'LJ2016A',
      name: 'Flange, Round Base, Type 1',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: "products/LJ1016A.png",
      tag: ["Flange", "Tube Fittings"]
    },
    {
      code: 'LJ1402S',
      name: 'Square Base Plate',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: "products/LJ1402S.png",
      tag: ["Flange", "Tube Fittings"]
    },
    {
      code: 'LJ2002S',
      name: 'Square Base Plate',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: "products/LJ1402S.png",
      tag: ["Flange", "Tube Fittings"]
    },
    {
      code: 'LJ15803',
      name: 'Outsided Wall Flange, Adjustable, Round Base Type 3',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: "products/LJ15803.png",
      tag: ["Flange", "Tube Fittings"]
    },
    {
      code: 'LJ20803',
      name: 'Outsided Wall Flange, Adjustable, Round Base Type 3',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: "products/LJ15803.png",
      tag: ["Flange", "Tube Fittings"]
    },
    {
      code: 'LJ2016U',
      name: 'Flange, Round Base, Type 2',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: "products/LJ2016U.png",
      tag: ["Flange", "Tube Fittings"]
    },
    {
      code: 'LJ15601A',
      name: 'Flange, Round Base, Type 3',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: "products/LJ15601A.png",
      tag: ["Flange", "Tube Fittings"]
    },
    {
      code: 'LJ20601A',
      name: 'Flange, Round Base, Type 3',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: "products/LJ15601A.png",
      tag: ["Flange", "Tube Fittings"]
    },
    //=============== End Cap ===============
    {
      code: 'LJ1018A',
      name: 'End Cap "Dome"',
      dimensions: 'Tube Size',
      spec: '1"',
      photo: "products/LJ1018A.png",
      tag: ["End Cap", "Tube Fittings"]
    },
    {
      code: 'LJ1218A',
      name: 'End Cap "Dome"',
      dimensions: 'Tube Size',
      spec: '1 1/4"',
      photo: "products/LJ1018A.png",
      tag: ["End Cap", "Tube Fittings"]
    },
    {
      code: 'LJ1518A',
      name: 'End Cap "Dome"',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: "products/LJ1018A.png",
      tag: ["End Cap", "Tube Fittings"]
    },
    {
      code: 'LJ2018A',
      name: 'End Cap "Dome"',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: "products/LJ1018A.png",
      tag: ["End Cap", "Tube Fittings"]
    },
    {
      code: 'LJ1019A',
      name: 'End Cap "Flat", Type 1',
      dimensions: 'Tube Size',
      spec: '1"',
      photo: "products/LJ1019A.png",
      tag: ["End Cap", "Tube Fittings"]
    },
    {
      code: 'LJ1219A',
      name: 'End Cap "Flat", Type 1',
      dimensions: 'Tube Size',
      spec: '1 1/4"',
      photo: "products/LJ1019A.png",
      tag: ["End Cap", "Tube Fittings"]
    },
    {
      code: 'LJ1519A',
      name: 'End Cap "Flat", Type 1',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: "products/LJ1019A.png",
      tag: ["End Cap", "Tube Fittings"]
    },
    {
      code: 'LJ2019A',
      name: 'End Cap "Flat", Type 1',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: "products/LJ1019A.png",
      tag: ["End Cap", "Tube Fittings"]
    },
    {
      code: 'LJ1030A',
      name: 'End Cap "Light Knock-In"',
      dimensions: 'Tube Size',
      spec: '1"',
      photo: "products/LJ1030A.png",
      tag: ["End Cap", "Tube Fittings"]
    },
    {
      code: 'LJ1530A',
      name: 'End Cap "Light Knock-In"',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: "products/LJ1030A.png",
      tag: ["End Cap", "Tube Fittings"]
    },
    {
      code: 'LJ2030A',
      name: 'End Cap "Light Knock-In"',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: "products/LJ1030A.png",
      tag: ["End Cap", "Tube Fittings"]
    },
    {
      code: 'LJ1525A',
      name: 'Handrail End CAP 45°',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: "products/LJ1525A.png",
      tag: ["End Cap", "Tube Fittings"]
    },
    {
      code: 'LJ2025A',
      name: 'Handrail End CAP 45°',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: "products/LJ1525A.png",
      tag: ["End Cap", "Tube Fittings"]
    },
    {
      code: 'LJ1526A',
      name: 'Handrail End CAP 90°',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: "products/LJ1526A.png",
      tag: ["End Cap", "Tube Fittings"]
    },
    {
      code: 'LJ2026A',
      name: 'Handrail End CAP 90°',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: "products/LJ1526A.png",
      tag: ["End Cap", "Tube Fittings"]
    },
    {
      code: 'LJ15739A',
      name: 'Handrail End Cap 90° Radiused Internal Fit',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: "products/LJ15739A.png",
      tag: ["End Cap", "Tube Fittings"]
    },
    {
      code: 'LJ20739A',
      name: 'Handrail End Cap 90° Radiused Internal Fit',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: "products/LJ15739A.png",
      tag: ["End Cap", "Tube Fittings"]
    },
    {
      code: 'LJ1519U',
      name: 'End Cap "Flat", Type 2',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: "products/LJ1519U.png",
      tag: ["End Cap", "Tube Fittings"]
    },
    {
      code: 'LJ2019U',
      name: 'End Cap "Flat", Type 2',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: "products/LJ1519U.png",
      tag: ["End Cap", "Tube Fittings"]
    },
    //=============== Glass Clamp and Holder ===============
    {
      code: 'LJ1523B',
      name: 'Glass Clip, Type 1',
      dimensions: 'Tube Size x Glass',
      spec: 'R 1 1/2"x 8-12 mm',
      photo: "products/LJ1523B.png",
      tag: ["Glass Clamp and Holder", "Tube Fittings"]
    },
    {
      code: 'LJ2023B',
      name: 'Glass Clip, Type 1',
      dimensions: 'Tube Size x Glass',
      spec: 'R 2"x 8-12 mm',
      photo: "products/LJ1523B.png",
      tag: ["Glass Clamp and Holder", "Tube Fittings"]
    },
    {
      code: 'LJS71R381',
      name: 'Glass Clamp, Square Type',
      dimensions: 'A x B x D x R x Glass (mm)',
      spec: '45 x 49 x 27 xR 38.1 x 6~10',
      photo: "products/LJS71R381.png",
      tag: ["Glass Clamp and Holder", "Tube Fittings"]
    },
    {
      code: 'LJS71R424',
      name: 'Glass Clamp, Square Type',
      dimensions: 'A x B x D x R x Glass (mm)',
      spec: '45 x 49 x 27 x R 42.4 x 6~10',
      photo: "products/LJS71R381.png",
      tag: ["Glass Clamp and Holder", "Tube Fittings"]
    },
    {
      code: 'LJS71R508',
      name: 'Glass Clamp, Square Type',
      dimensions: 'A x B x D x R x Glass (mm)',
      spec: '45 x 49 x 27 x R 50.8 x 6~10',
      photo: "products/LJS71R381.png",
      tag: ["Glass Clamp and Holder", "Tube Fittings"]
    },
    {
      code: 'LJS72F',
      name: 'Glass Clamp, Square Type',
      dimensions: 'A x B x D x R x Glass (mm)',
      spec: '45 x 45 x 27 x (FLAT) x 6~10 ',
      photo: "products/LJS71R381.png",
      tag: ["Glass Clamp and Holder", "Tube Fittings"]
    },
    {
      code: 'LJS73R381',
      name: 'Glass Clamp, Square Type',
      dimensions: 'A x B x D x R x Glass (mm)',
      spec: '55 x 60 x 33 x R 38.1 x 8~12',
      photo: "products/LJS71R381.png",
      tag: ["Glass Clamp and Holder", "Tube Fittings"]
    },
    {
      code: 'LJS73R424',
      name: 'Glass Clamp, Square Type',
      dimensions: 'A x B x D x R x Glass (mm)',
      spec: '55 x 60 x 33 x R 42.4 x 8~12',
      photo: "products/LJS71R381.png",
      tag: ["Glass Clamp and Holder", "Tube Fittings"]
    },
    {
      code: 'LJS73R508',
      name: 'Glass Clamp, Square Type',
      dimensions: 'A x B x D x R x Glass (mm)',
      spec: '55 x 60 x 33 x R 50.8 x 8~12',
      photo: "products/LJS71R381.png",
      tag: ["Glass Clamp and Holder", "Tube Fittings"]
    },
    {
      code: 'LJS74F',
      name: 'Glass Clamp, Square Type',
      dimensions: 'A x B x D x R x Glass (mm)',
      spec: '55 x 55 x 33 x (FLAT) x 8~12 ',
      photo: "products/LJS71R381.png",
      tag: ["Glass Clamp and Holder", "Tube Fittings"]
    },
    {
      code: 'LJD75R381',
      name: 'Glass Clamp, D Type',
      dimensions: 'A x B x D x R x Glass (mm)',
      spec: '50 x 53 x 33 x R 38.1 x 8~12',
      photo: "products/LJD75R381.png",
      tag: ["Glass Clamp and Holder", "Tube Fittings"]
    },
    {
      code: 'LJD75R424',
      name: 'Glass Clamp, D Type',
      dimensions: 'A x B x D x R x Glass (mm)',
      spec: '50 x 53 x 33 x R 42.4 x 8~12',
      photo: "products/LJD75R381.png",
      tag: ["Glass Clamp and Holder", "Tube Fittings"]
    },
    {
      code: 'LJD75R508',
      name: 'Glass Clamp, D Type',
      dimensions: 'A x B x D x R x Glass (mm)',
      spec: '50 x 53 x 33 x R 50.8 x 8~12',
      photo: "products/LJD75R381.png",
      tag: ["Glass Clamp and Holder", "Tube Fittings"]
    },
    {
      code: 'LJD76F',
      name: 'Glass Clamp, D Type',
      dimensions: 'A x B x D x R x Glass (mm)',
      spec: '65 x 60 x 33 (FLAT) x 8~12',
      photo: "products/LJD75R381.png",
      tag: ["Glass Clamp and Holder", "Tube Fittings"]
    },
    {
      code: 'LJD81R381',
      name: 'Glass Clamp, D Type',
      dimensions: 'A x B x D x R x Glass (mm)',
      spec: '40 x 53 x 23 x R 38.1 x 6~10',
      photo: "products/LJD75R381.png",
      tag: ["Glass Clamp and Holder", "Tube Fittings"]
    },
    {
      code: 'LJD81R424',
      name: 'Glass Clamp, D Type',
      dimensions: 'A x B x D x R x Glass (mm)',
      spec: '40 x 53 x 23 x R 42.4 x 6~10',
      photo: "products/LJD75R381.png",
      tag: ["Glass Clamp and Holder", "Tube Fittings"]
    },
    {
      code: 'LJD81R508',
      name: 'Glass Clamp, D Type',
      dimensions: 'A x B x D x R x Glass (mm)',
      spec: '40 x 53 x 23 x R 50.8 x 6~10',
      photo: "products/LJD75R381.png",
      tag: ["Glass Clamp and Holder", "Tube Fittings"]
    },
    {
      code: 'LJD82F',
      name: 'Glass Clamp, D Type',
      dimensions: 'A x B x D x R x Glass (mm)',
      spec: '40 x 50 x 23 x (FLAT) x 6~10',
      photo: "products/LJD75R381.png",
      tag: ["Glass Clamp and Holder", "Tube Fittings"]
    },
    {
      code: 'LJD83R381',
      name: 'Glass Clamp, D Type',
      dimensions: 'A x B x D x R x Glass (mm)',
      spec: '45 x 66 x 27 x R 38.1 x 8~12',
      photo: "products/LJD75R381.png",
      tag: ["Glass Clamp and Holder", "Tube Fittings"]
    },
    {
      code: 'LJD83R424',
      name: 'Glass Clamp, D Type',
      dimensions: 'A x B x D x R x Glass (mm)',
      spec: '45 x 66 x 27 x R 42.4 x 8~12',
      photo: "products/LJD75R381.png",
      tag: ["Glass Clamp and Holder", "Tube Fittings"]
    },
    {
      code: 'LJD83R508',
      name: 'Glass Clamp, D Type',
      dimensions: 'A x B x D x R x Glass (mm)',
      spec: '45 x 66 x 27 x R 50.8 x 8~12',
      photo: "products/LJD75R381.png",
      tag: ["Glass Clamp and Holder", "Tube Fittings"]
    },
    {
      code: 'LJD84F',
      name: 'Glass Clamp, D Type',
      dimensions: 'A x B x D x R x Glass (mm)',
      spec: '45 x 62 x 27 (FLAT) x 8~12',
      photo: "products/LJD75R381.png",
      tag: ["Glass Clamp and Holder", "Tube Fittings"]
    },
    {
      code: 'LJB90-SH',
      name: 'Glass Clip, Type 2',
      dimensions: 'Size x Glass (mm)',
      spec: '(90 x 50 x 55) x 10~12',
      photo: "products/LJB90.png",
      tag: ["Glass Clamp and Holder", "Tube Fittings"]
    },
    {
      code: 'LJB90G-SH',
      name: 'Glass Clip Type 3',
      dimensions: 'Size x Glass (mm)',
      spec: '(90 x 58 x 55) x 10~12',
      photo: "products/LJB90G.png",
      tag: ["Glass Clamp and Holder", "Tube Fittings"]
    },
    {
      code: 'LJ01SPG',
      name: 'Glass Holder Type 1',
      dimensions: 'Glass (mm)',
      spec: '10~12 mm',
      photo: "products/LJ01SPG.png",
      tag: ["Glass Clamp and Holder", "Tube Fittings"]
    },
    {
      code: 'LJ03SPG',
      name: 'Glass Holder Type 2',
      dimensions: 'Glass (mm)',
      spec: '10~12 mm',
      photo: "products/LJ03SPG.png",
      tag: ["Glass Clamp and Holder", "Tube Fittings"]
    },
    {
      code: 'LJ04SPG',
      name: 'Glass Holder Type 3',
      dimensions: 'Glass (mm)',
      spec: '10~12 mm',
      photo: "products/LJ04SPG.png",
      tag: ["Glass Clamp and Holder", "Tube Fittings"]
    },
    //=============== Support ===============
    {
      code: 'LJ15602',
      name: 'Rail Support Type - 1',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ15602.png',
      tag: ['Support', 'Tube Fittings'],
    },
    {
      code: 'LJ20602',
      name: 'Rail Support Type - 1',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: 'products/LJ15602.png',
      tag: ['Support', 'Tube Fittings'],
    },
    {
      code: 'LJ15603',
      name: 'Rail Support Type - 2',
      dimensions: 'Tube Size',
      spec: '1 1/2"',
      photo: 'products/LJ15603.png',
      tag: ['Support', 'Tube Fittings'],
    },
    {
      code: 'LJ20603',
      name: 'Rail Support Type - 2',
      dimensions: 'Tube Size',
      spec: '2"',
      photo: 'products/LJ15603.png',
      tag: ['Support', 'Tube Fittings'],
    },
    {
      code: 'LJ1528A',
      name: 'Handrail Wall Support "Radiused"',
      dimensions: 'ØR',
      spec: '1 1/2"',
      photo: 'products/LJ1528A.png',
      tag: ['Support', 'Tube Fittings'],
    },
    {
      code: 'LJ2028A',
      name: 'Handrail Wall Support "Radiused"',
      dimensions: 'ØR',
      spec: '2"',
      photo: 'products/LJ1528A.png',
      tag: ['Support', 'Tube Fittings'],
    },
    {
      code: 'LJ15710RA 381',
      name: 'Handrail Support "Radiused" Type-2',
      dimensions: 'Tube Size x ØR',
      spec: '1 1/2" x 1 1/2"',
      photo: 'products/LJ15710RA.png',
      tag: ['Support', 'Tube Fittings'],
    },
    {
      code: 'LJ15710RA 508',
      name: 'Handrail Support "Radiused" Type-2',
      dimensions: 'Tube Size x ØR',
      spec: '1 1/2" x 2"',
      photo: 'products/LJ15710RA.png',
      tag: ['Support', 'Tube Fittings'],
    },
    {
      code: 'LJ20710RA 381',
      name: 'Handrail Support "Radiused" Type-2',
      dimensions: 'Tube Size x ØR',
      spec: '2" x 1 1/2"',
      photo: 'products/LJ15710RA.png',
      tag: ['Support', 'Tube Fittings'],
    },
    {
      code: 'LJ20710RA 508',
      name: 'Handrail Support "Radiused" Type-2',
      dimensions: 'Tube Size x ØR',
      spec: '2" x 2"',
      photo: 'products/LJ15710RA.png',
      tag: ['Support', 'Tube Fittings'],
    },
    {
      code: 'LJ0473A',
      name: 'Cross Saddle',
      dimensions: 'Tube Size x ØR',
      spec: '1/2" x 1 1/2"',
      photo: 'products/LJ0473A.png',
      tag: ['Support', 'Tube Fittings'],
    },
    {
      code: 'LJ0474A',
      name: 'Cross Saddle',
      dimensions: 'Tube Size x ØR',
      spec: '1/2" x 2"',
      photo: 'products/LJ0473A.png',
      tag: ['Support', 'Tube Fittings'],
    },
    {
      code: 'LJ0573A',
      name: 'Cross Saddle',
      dimensions: 'Tube Size x ØR',
      spec: '5/8" x 1 1/2"',
      photo: 'products/LJ0473A.png',
      tag: ['Support', 'Tube Fittings'],
    },
    {
      code: 'LJ0574A',
      name: 'Cross Saddle',
      dimensions: 'Tube Size x ØR',
      spec: '5/8" x 2"',
      photo: 'products/LJ0473A.png',
      tag: ['Support', 'Tube Fittings'],
    },
    {
      code: 'LJ0673A',
      name: 'Cross Saddle',
      dimensions: 'Tube Size x ØR',
      spec: '3/4" x 1 /12"',
      photo: 'products/LJ0473A.png',
      tag: ['Support', 'Tube Fittings'],
    },
    {
      code: 'LJ0674A',
      name: 'Cross Saddle',
      dimensions: 'Tube Size x ØR',
      spec: '3/4" x 2"',
      photo: 'products/LJ0473A.png',
      tag: ['Support', 'Tube Fittings'],
    },
    {
      code: 'LJ0473B',
      name: 'Cross Saddle Blind Hole',
      dimensions: 'Tube Size x ØR',
      spec: '1/2" x 1 1/2"',
      photo: 'products/LJ0473B.png',
      tag: ['Support', 'Tube Fittings'],
    },
    {
      code: 'LJ0474B',
      name: 'Cross Saddle Blind Hole',
      dimensions: 'Tube Size x ØR',
      spec: '1/2" x 2"',
      photo: 'products/LJ0473B.png',
      tag: ['Support', 'Tube Fittings'],
    },
    {
      code: 'LJ0573B',
      name: 'Cross Saddle Blind Hole',
      dimensions: 'Tube Size x ØR',
      spec: '5/8" x 1 1/2"',
      photo: 'products/LJ0473B.png',
      tag: ['Support', 'Tube Fittings'],
    },
    {
      code: 'LJ0574B',
      name: 'Cross Saddle Blind Hole',
      dimensions: 'Tube Size x ØR',
      spec: '5/8" x 2"',
      photo: 'products/LJ0473B.png',
      tag: ['Support', 'Tube Fittings'],
    },
    {
      code: 'LJ0673B',
      name: 'Cross Saddle Blind Hole',
      dimensions: 'Tube Size x ØR',
      spec: '3/4" x 1 /12"',
      photo: 'products/LJ0473B.png',
      tag: ['Support', 'Tube Fittings'],
    },
    {
      code: 'LJ0674B',
      name: 'Cross Saddle Blind Hole',
      dimensions: 'Tube Size x ØR',
      spec: '3/4" x 2"',
      photo: 'products/LJ0473B.png',
      tag: ['Support', 'Tube Fittings'],
    },
    {
      code: 'LJ15711RA',
      name: 'Handrail Support "Radiused" Type-3',
      dimensions: 'ØR',
      spec: '1 1/2"',
      photo: 'products/LJ15711RA.png',
      tag: ['Support', 'Tube Fittings'],
    },
    {
      code: 'LJ20711RA',
      name: 'Handrail Support "Radiused" Type-3',
      dimensions: 'ØR',
      spec: '2"',
      photo: 'products/LJ15711RA.png',
      tag: ['Support', 'Tube Fittings'],
    },
    {
      code: 'LJ151BK',
      name: 'Handrail Support For Glass, "Radiused" Type 1 (Adjustable)',
      dimensions: 'ØR, Glass (mm)',
      spec: '1 1/2" x 8~12mm',
      photo: 'products/LJ151BK.png',
      tag: ['Support', 'Tube Fittings'],
    },
    {
      code: 'LJ201BK',
      name: 'Handrail Support For Glass, "Radiused" Type 1 (Adjustable)',
      dimensions: 'ØR, Glass (mm)',
      spec: '2" x 8~12mm',
      photo: 'products/LJ151BK.png',
      tag: ['Support', 'Tube Fittings'],
    },
    {
      code: 'LJ152BK',
      name: 'Handrail Support For Glass, "Radiused" Type 2 (Fixed)',
      dimensions: 'ØR, Glass (mm)',
      spec: '1 1/2" x 8~12mm',
      photo: 'products/LJ152BK.png',
      tag: ['Support', 'Tube Fittings'],
    },
    {
      code: 'LJ202BK',
      name: 'Handrail Support For Glass, "Radiused" Type 2 (Fixed)',
      dimensions: 'ØR, Glass (mm)',
      spec: '2" x 8~12mm',
      photo: 'products/LJ152BK.png',
      tag: ['Support', 'Tube Fittings'],
    },
    {
      code: 'LJ155BK',
      name: 'Handrail Support For Glass, "Radiused" Type 3 (Adjustable)',
      dimensions: 'ØR, Glass (mm)',
      spec: '1 1/2" x 8~12mm',
      photo: 'products/LJ155BK.png',
      tag: ['Support', 'Tube Fittings'],
    },
    {
      code: 'LJ205BK',
      name: 'Handrail Support For Glass, "Radiused" Type 3 (Adjustable)',
      dimensions: 'ØR, Glass (mm)',
      spec: '2" x 8~12mm',
      photo: 'products/LJ155BK.png',
      tag: ['Support', 'Tube Fittings'],
    },
    {
      code: 'LJ203BK',
      name: 'Handrail Support For Glass & Wall',
      dimensions: 'ØR, Glass (mm)',
      spec: '8~12mm',
      photo: 'products/LJ203BK.png',
      tag: ['Support', 'Tube Fittings'],
    },
    //=============== Square Type ===============
    {
      code: 'LJ2019S',
      name: 'End Cap "Flat"',
      dimensions: 'Tube Size',
      spec: '2" x 2"',
      photo: 'products/LJ2019S.png',
      tag: ['Square Type', 'Tube Fittings'],
    },
    {
      code: 'LJ2004S',
      name: 'Flush Joiner "In-Line"',
      dimensions: 'Tube Size',
      spec: '2" x 2"',
      photo: 'products/LJ2004S.png',
      tag: ['Square Type', 'Tube Fittings'],
    },
    {
      code: 'LJ2002S',
      name: 'Flush Joiner (90°)',
      dimensions: 'Tube Size',
      spec: '2"x 2"',
      photo: 'products/LJ2002S.png',
      tag: ['Square Type', 'Tube Fittings'],
    },
    {
      code: 'LJ2005S',
      name: 'Flush Joiner "Tee"',
      dimensions: 'Tube Size',
      spec: '2"x 2"',
      photo: 'products/LJ2005S.png',
      tag: ['Square Type', 'Tube Fittings'],
    },
    {
      code: 'LJ2006S',
      name: 'Flush Joiner "90° Tee"',
      dimensions: 'Tube Size',
      spec: '2"x 2"',
      photo: 'products/LJ2006S.png',
      tag: ['Square Type', 'Tube Fittings'],
    },
    {
      code: 'LJ2014S',
      name: 'Oblong Base Plate Flange',
      dimensions: 'Tube Size',
      spec: '2"x 2"',
      photo: 'products/LJ2014S.png',
      tag: ['Square Type', 'Tube Fittings'],
    },
    {
      code: 'LJ2016S',
      name: 'Square Base Plate / Flange',
      dimensions: 'Tube Size',
      spec: '2"x 2"',
      photo: 'products/LJ2016S.png',
      tag: ['Square Type', 'Tube Fittings'],
    },
    {
      code: 'LJ2015S',
      name: 'Wall Stop Flange 37°',
      dimensions: 'Tube Size',
      spec: '2"x 2"',
      photo: 'products/LJ2015S.png',
      tag: ['Square Type', 'Tube Fittings'],
    },
    {
      code: 'LJ315APS',
      name: 'Adjustable Rail Support "Flat Top"',
      dimensions: 'Tube Size x ØR',
      spec: '2" x 2" x FLAT',
      photo: 'products/LJ315APS.png',
      tag: ['Square Type', 'Tube Fittings'],
    },
    {
      code: 'LJ2020S',
      name: 'Post Reducer Square "Round In-Line"',
      dimensions: 'Tube Size x ØR',
      spec: '2" x 2" x 2"',
      photo: 'products/LJ2020S.png',
      tag: ['Square Type', 'Tube Fittings'],
    },
    {
      code: 'LJ2021S',
      name: 'Post Reducer Square "Round Adjustable"',
      dimensions: 'Tube Size x ØR',
      spec: '2" x 2" x 2"',
      photo: 'products/LJ2021S.png',
      tag: ['Square Type', 'Tube Fittings'],
    },
    {
      code: 'LJ2022S',
      name: 'Post Rreducer Square "Round 90° Corner"',
      dimensions: 'Tube Size x ØR',
      spec: '2" x 2" x 2"',
      photo: 'products/LJ2022S.png',
      tag: ['Square Type', 'Tube Fittings'],
    },
    //=============== Perpendicular Joiner ===============
    {
      code: 'LJ20314A-2',
      name: 'Perpendicular Joiner "37° External Cap"',
      dimensions: 'Tube Size x ØR',
      spec: '',
      photo: 'products/LJ20314A-2.png',
      tag: ['Perpendicular Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ20313A-2',
      name: 'Perpendicular Joiner "External Cap"',
      dimensions: 'Tube Size x ØR',
      spec: '2" x 2"',
      photo: 'products/LJ20313A-2.png',
      tag: ['Perpendicular Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1527A - 1 1/2',
      name: 'Perpendicular Joiner "Flush Fitting"',
      dimensions: 'Tube Size x ØR',
      spec: '1 1/2" x 1 1/2"',
      photo: 'products/LJ1527A.png',
      tag: ['Perpendicular Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ1527A - 2',
      name: 'Perpendicular Joiner "Flush Fitting"',
      dimensions: 'Tube Size x ØR',
      spec: '1 1/2" x 2"',
      photo: 'products/LJ1527A.png',
      tag: ['Perpendicular Joiner', 'Tube Fittings'],
    },
    {
      code: 'LJ2027A - 2',
      name: 'Perpendicular Joiner "Flush Fitting"',
      dimensions: 'Tube Size x ØR',
      spec: '2" x 2"',
      photo: 'products/LJ1527A.png',
      tag: ['Perpendicular Joiner', 'Tube Fittings'],
    },
    //=============== Rail Post ===============
    {
      code: 'LJ201BL',
      name: 'Rail post Type 1',
      dimensions: 'Glass (mm)',
      spec: '10~12 mm',
      photo: 'products/LJ201BL.png',
      tag: ['Rail Post', 'Tube Fittings'],
    },
    {
      code: 'LJ307BL',
      name: 'Rail post Type 2',
      dimensions: 'Glass (mm)',
      spec: '10~12 mm',
      photo: 'products/LJ307BL.png',
      tag: ['Rail Post', 'Tube Fittings'],
    },
    //=============== Grap Bar ===============
    {
      code: 'LJ1201GB',
      name: 'Grab Bar',
      dimensions: 'Tube Size x Length',
      spec: '31.8 x 600 mm',
      photo: 'products/LJ1201GB.png',
      tag: ['Grab Bar', 'Tube Fittings'],
    },
    {
      code: 'LJ1501GB',
      name: 'Grab Bar',
      dimensions: 'Tube Size x Length',
      spec: '38.1 x 600 mm',
      photo: 'products/LJ1201GB.png',
      tag: ['Grab Bar', 'Tube Fittings'],
    },
    {
      code: 'LJ1201FGB',
      name: 'Folding Grab bar',
      dimensions: 'Tube Size x Length',
      spec: '31.8 x 800 mm',
      photo: 'products/LJ1201FGB.png',
      tag: ['Grab Bar', 'Tube Fittings'],
    },
  ];

  constructor() { }

  getProducts(): Product[] {
    return this.products;
  }
}
